## Aradhya Kumar
## 2006542
## TTL LAB 6 20 FEB
## IT - 6

In [1]:
#create an empty and full array
import numpy as np
arr1 = np.array([])
arr2 = np.array([1,2,3,4,5])
print(arr1)
print(arr2)

[]
[1 2 3 4 5]


In [2]:
#create an array of full 0s
import numpy as np
arr1 = np.array([0,0,0,0,0])
print(arr1)

[0 0 0 0 0]


In [3]:
#create an array of full 1s
import numpy as np
arr1 = np.array([1,1,1,1,1])
print(arr1)

[1 1 1 1 1]


In [5]:
#check if a row exists or not
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20]])

# view array
print(arr)

print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [10]:
#reverse an array
import numpy as np

arr= np.array([9, 'hello', 'how', 'are', 'you?', 1])
result = np.flipud(arr)
print("Reverse array",(result))
print("Original array", arr)

Reverse array ['1' 'you?' 'are' 'how' 'hello' '9']
Original array ['9' 'hello' 'how' 'are' 'you?' '1']


In [9]:
#removing a non-numeric row from the array
import numpy as np

# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],[41, np.nan, np.nan]])

print("Given array:")
print(n_arr)

print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])


Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [11]:
#mostfrequent value in the above array
import numpy as np


# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [12]:
#getting  help on add function
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
#create three arrays of 10 zeroes 10 ones and 5 fives in numpy
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(5)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5.]


In [14]:
#create an array of the integers from 30 to 70 
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
#create an array of all the even integers from 30 to 70 
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [18]:
#create a 3x3 identity matrix
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix: \n')
print(array_2D)

3x3 matrix: 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#swap rows and coloumns of a given array in reverse order
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


In [20]:
#multiply two given arrays of same size element by element
import numpy as np 
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]


In [21]:
#extract all numbers from a given array
import numpy as np  
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n = 5
print("\nElements of the said array greater than",n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than",n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
import numpy as np 
arr1 = np.array([5,3,1,4,7,8,2,9,0,11])
print('original array:',arr1)
newarr = np.sort(arr1)
print('sorted array:',newarr)

original array: [ 5  3  1  4  7  8  2  9  0 11]
sorted array: [ 0  1  2  3  4  5  7  8  9 11]
