## Name : Aradhya Kumar
## Roll no. : 2006542

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

1.23.5


In [5]:
import numpy as np 
arr = np.array(45)
print(arr)

45


In [7]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [17]:
import numpy as np 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [22]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print('3rd element in second row ',arr2[1,2])

[[1 2 3]
 [4 5 6]]
3rd element in second row  6


In [24]:
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr[0,1,2])

6


In [26]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print('Last element in the matrix',arr2[1,-1])

Last element in the matrix 6


In [30]:
import numpy as np 
arr1 = np.array([1,2,3,4,5])
print(arr1[::2])

[1 3 5]


In [33]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,1:4])

[5 6]


In [36]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[0:2,2])

[3 6]


In [45]:
import numpy as np
arr = np.array(['apple','banana','mango'])
print(arr)

['apple' 'banana' 'mango']


In [44]:
import numpy as np 
arr = np.array([1,2,3,4,5],dtype='S')
#dtype = datatype
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [47]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [49]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [53]:
arr = np.array([1,2,3,4,5,6])
newarr = arr.reshape(2,3)
print(newarr)

[[1 2 3]
 [4 5 6]]


In [54]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [55]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [59]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,20,30],[40,50,60]])
arr = np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


In [61]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
